apiVersion: apps/v1
kind: Deployment
metadata:
  name: trader
  namespace: polymarket-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trader
  template:
    metadata:
      labels:
        app: trader
    spec:
      containers:
        - name: trader
          image: polymarket-bot-trader:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: polymarket-config
