pair: BTC
polymarket_asset_id: ""
polymarket_market_id: ""
polymarket_market_ws_url: "wss://ws-subscriptions-clob.polymarket.com/ws/market"
binance_symbol: "BTCUSDT"
binance_ws_url: "wss://stream.binance.com:9443/ws"

